name: Hello World Workflow

on: push

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: print Hello World
        run: echo "Hello, World" $$ sleep 30s
      - name: print Hello New Era Solutions
        run: print "Hello, New Era Solutions" && sleep 30

        
